const GlobalConfig = {
    DATA_ATTRIBUTE_PREFIX: "cb",
    LAZY_INITIALIZATION_MARGIN: "100px",
    DEFAULT_LINE_HEIGHT: 2,
    DEFAULT_LINE_HEIGHT_UNIT: "rem",
    DEFAULT_NO_CODE_VIEW_SELECTED_ELEMENT_HEIGHT: "50rem",
    DEFAULT_NO_CODE_VIEW_SELECTED_TEXT: "No code view selected",
    DEFAULT_CODE_VIEW_BUTTON_TEXT: "unnamed",
    DEFAULT_FILE_BUTTON_TEXT: "unnamed",
    DEFAULT_PROJECT_NAME: "unnamed",
    DEFAULT_PROJECT_FOLDER_STRUCTURE_HEADING: "Folder structure",
    DEFAULT_PROJECT_PACKAGES_HEADING: "Packages",
    DEFAULT_DEFAULT_PACKAGE_NAME: "default",
    DEFAULT_FOLDER_ANIMATION_SPEED: 200,
    DEFAULT_FOLDER_ANIMATION_EASING_FUNCTION: "ease-in-out"
}

export default GlobalConfig;